// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASIet7wqGRpkv43qYT9U4OVD1YkMzc4Vc',
    appId: '1:83631225567:web:e06eacff3d44e3588a076a',
    messagingSenderId: '83631225567',
    projectId: 'medical-app-9a5ea',
    authDomain: 'medical-app-9a5ea.firebaseapp.com',
    storageBucket: 'medical-app-9a5ea.firebasestorage.app',
    measurementId: 'G-480L50EWTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjUox307RHXhiCTiZS29IVBZlFxYVdNFE',
    appId: '1:83631225567:android:1f19735e918bcac58a076a',
    messagingSenderId: '83631225567',
    projectId: 'medical-app-9a5ea',
    storageBucket: 'medical-app-9a5ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGEE7FXi18PvE6Fo6aoi31D429EnKJtkA',
    appId: '1:83631225567:ios:43eae4ab67b52fec8a076a',
    messagingSenderId: '83631225567',
    projectId: 'medical-app-9a5ea',
    storageBucket: 'medical-app-9a5ea.firebasestorage.app',
    iosBundleId: 'com.example.medicalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGEE7FXi18PvE6Fo6aoi31D429EnKJtkA',
    appId: '1:83631225567:ios:43eae4ab67b52fec8a076a',
    messagingSenderId: '83631225567',
    projectId: 'medical-app-9a5ea',
    storageBucket: 'medical-app-9a5ea.firebasestorage.app',
    iosBundleId: 'com.example.medicalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASIet7wqGRpkv43qYT9U4OVD1YkMzc4Vc',
    appId: '1:83631225567:web:1c2672425c29abd48a076a',
    messagingSenderId: '83631225567',
    projectId: 'medical-app-9a5ea',
    authDomain: 'medical-app-9a5ea.firebaseapp.com',
    storageBucket: 'medical-app-9a5ea.firebasestorage.app',
    measurementId: 'G-ET8DPCVX89',
  );
}
